### ISSUE TITLE
Where to edit environment variable in updated code of index.php

### ISSUE THREAD

**Issue by deepak950** [kodekloudhub/learning-app-ecommerce#16]
index.php is updated to use environment variable to call the mysql creds. In which file It needs to edit, is it system ENV file ?

![image](https://github.com/kodekloudhub/learning-app-ecommerce/assets/8769582/a943e69a-4850-4eaa-8e94-59985bf5b7ae)

**Comment by mobster1425** [comment]
i think you have to create your env file

**Comment by mobster1425** [comment]
the env should contain this =  // $link = mysqli_connect('172.20.1.101', 'ecomuser', 'ecompassword', 'ecomdb');
                        // Fetch database connection details directly from environment variables
                        $dbHost = getenv('DB_HOST');
                        $dbUser = getenv('DB_USER');
                        $dbPassword = getenv('DB_PASSWORD');
                        $dbName = getenv('DB_NAME');

**Comment by nimeshmora** [comment]
@deepak950 Updated the README.md file on how to create .env file and fetch environment specific details. Please check!

**Comment by nimeshmora** [comment]
@deepak950 Updated the README.md file on how to create .env file and fetch environment specific details. Please check!
